name: Release Handler

on:
  push:
    branches:
      - dev
    paths:
      - '**.zip'     # Trigger only if .zip is pushed

jobs:
  deploy:
    runs-on: self-hosted   # Runs on your Windows 11 machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true   # Important if using Git LFS for large files

      - name: Copy release zip to local folder
        run: |
          echo "Copying zip to C:\server_release"
          mkdir C:\server_release || echo "Folder exists"
          for %f in (*.zip) do copy "%f" C:\server_release\

      - name: Run Python installation script
        run: |
          echo "Running install script..."
          python C:\CenTrak\Framework\Framework\MM_Badge\Core_Server_Installation\run_and_upload.py
