name: Test Windows Runner

on:
  push:
    branches:
      - main   # change if your default branch is not 'main'

jobs:
  check-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from my Windows 11 self-hosted runner 🎉"

      - name: Print system info
        run: systeminfo
